fix_01
Mr-Cheen1/todo_list pull request #1
Opened 2024-04-10 16:52 UTC by Mr-Cheen1

2024-04-14 08:59 UTC, vladislavmass requested changes

2024-04-14 08:59 UTC, vladislavmass commented on todo/server/db/db.go
> +	host := os.Getenv("DB_HOST")
Код отвечающий за работу с базой не должен ничего знать о том, как хранится конфигурация. Все данные для подключения он должен получать из параметров вызывающего кода

2024-04-14 08:59 UTC, vladislavmass commented on todo/server/handlers/task_handlers.go
> +	if task.Status != "в процессе" && task.Status != "завершено" {
Передавать статусы в виде текстовых строк не самая хорошая идея. Как минимум это затруднит локализацю и любая разница в написание создаст проблем. Чаще всего для  этих целей используют int

2024-04-14 08:59 UTC, vladislavmass commented on todo/server/db/db_handlers.go
> +	Date   time.Time `json:"date"`
Это дата чего? Создания задачи или до какого надо сделать? В идеале нужны обе даты. А также датам нужна валидация. Если это даты до которой надо сделать, то она никак не может быть до текущего момент,

2024-04-14 08:59 UTC, vladislavmass commented on todo/server/db/db_handlers.go
> +		query += " WHERE status = '" + statusFilter + "'"
Таким образом работать с sql не допустима. Все аргументы должны передаваться как плейсхолдеры

2024-04-14 08:59 UTC, vladislavmass commented on todo/server/handlers/task_handlers.go
> +	err := json.NewDecoder(r.Body).Decode(&task)
Тело запроса необходимо закрывать

2024-04-15 02:43 UTC, Mr-Cheen1 commented on todo/server/db/db_handlers.go
> +	Date   time.Time `json:"date"`
Поле Date хранит текущую дату , в клиентской части "const currentDate = new Date();" дата и время обновляются при любой манипуляции с задачей будь то создание, обновление статуса или редактирование задачи. Таким образом пользователь может легко увидеть в начале списка последнюю завершенную задачу путем - отфильтровав по статусу и отсортировав по убыванию список задач. Я рассматривал вариант с добавлением 2 дат где одна бы указывала на момент создания задачи а вторая бы указывала на планируемое завершение, но при моделировании ситуации когда пользователь бы завершал задачу раньше планируемой даты и менял бы статус на завершено , во второй бы дате (планируемой к завершению задачи) не было бы смысла. Вторая дата планируемого завершения задачи была бы логична если бы мы проводили статистику по выполнению задач или еще какую логику. В условиях вроде как только: "Реализована возможность просмотра задач по различным критериям, например, по статусу, дате создания и т.д." , просмотр и вроде как этим я и руководствовался.

2024-04-15 06:47 UTC, vladislavmass commented on todo/server/db/db_handlers.go
> +	Date   time.Time `json:"date"`
Вообще TODO лист это инструмент планирование. Поэтому я все же рекомендовал ввести поля дата создания и предполагаемая дата завершения. Так как это функционал, который отвечает именно за планирование. Если есть желание хранить даты перехода событий из статуса в статус, то для этого правильнее было бы создать отдельную таблицу и там отслеживать статус задачи по датам.

2024-04-15 08:32 UTC, Mr-Cheen1 commented on todo/server/db/db_handlers.go
> +	Date   time.Time `json:"date"`
так а логику валидации какую тогда можно добавить(речь про 2 даты) , что то типа дата завершения не должна быть ровна или меньше даты создания?

2024-04-15 09:18 UTC, vladislavmass commented on todo/server/db/db_handlers.go
> +	Date   time.Time `json:"date"`
Да, именно так

2024-04-19 11:50 UTC, vladislavmass approved these changes

2024-04-19 12:15 UTC, Mr-Cheen1 commented
Спасибо за рекомендации по ДЗ и проекту. Да ветку хотелось бы смерджить.

2024-04-19 15:56 UTC, merged